### ISSUE TITLE
Cannot set isolationLevel with com.arjuna.ats.jdbc.isolationLevel with Spring Boot

### ISSUE THREAD

**Issue by hasancansaral** [snowdrop/narayana-spring-boot#24]
The default isolation level with Narayana is:

```
private volatile int isolationLevel = Connection.TRANSACTION_SERIALIZABLE;
```

but this gives me the following error with stack trace because I am using Percona:

```
Caused by: java.sql.SQLException: Percona-XtraDB-Cluster doesn't recommend using SERIALIZABLE isolation with pxc_strict_mode = ENFORCING
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:545)
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:513)
	at com.mysql.cj.jdbc.exceptions.SQLExceptionsMapping.translateException(SQLExceptionsMapping.java:115)
	at com.mysql.cj.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:1983)
	at com.mysql.cj.jdbc.ConnectionImpl.setTransactionIsolation(ConnectionImpl.java:4023)
	at com.mysql.cj.jdbc.ConnectionWrapper.setTransactionIsolation(ConnectionWrapper.java:249)
	at com.arjuna.ats.internal.jdbc.drivers.modifiers.IsSameRMModifier.setIsolationLevel(IsSameRMModifier.java:77)
	at com.arjuna.ats.internal.jdbc.ConnectionImple.getConnection(ConnectionImple.java:826)
	at com.arjuna.ats.internal.jdbc.ConnectionImple.init(ConnectionImple.java:143)
	at com.arjuna.ats.internal.jdbc.ConnectionImple.<init>(ConnectionImple.java:111)
	at com.arjuna.ats.internal.jdbc.ConnectionManager.create(ConnectionManager.java:147)
	at me.snowdrop.boot.narayana.core.jdbc.NarayanaDataSource.getConnection(NarayanaDataSource.java:55)
	at org.springframework.jdbc.datasource.DataSourceUtils.fetchConnection(DataSourceUtils.java:158)
	at org.springframework.jdbc.datasource.DataSourceUtils.doGetConnection(DataSourceUtils.java:116)
	at org.springframework.jdbc.datasource.DataSourceUtils.getConnection(DataSourceUtils.java:79)
	... 33 common frames omitted
```

`com.arjuna.ats.jdbc.isolationLevel` property doesn't seem to take effect, nor setting `System.setProperty("com.arjuna.ats.jdbc.isolationLevel", "1")` does. It is always 8 (the default) in `IsSameRMModifier`. This is also in the logs before the exception:

```
o.h.e.j.e.i.JdbcEnvironmentInitiator     : HHH000342: Could not obtain connection to query metadata : Percona-XtraDB-Cluster doesn't recommend using SERIALIZABLE isolation with pxc_strict_mode = ENFORCING
```

How do I overcome this?

**Comment by gytis** [comment]
Hi, @hasancansaral.

I just tried setting a system property "com.arjuna.ats.jdbc.isolationLevel=1" both via Maven and IDE and isolation level was set correctly. How do you configure it?

**Comment by gytis** [comment]
Closing the issue as there hasn't been any activity for almost a month.
